AWSTemplateFormatVersion: "2010-09-09"

Description: 'CloudFormation Template for creating destination S3 replication bucket.
 Run this cloudformation template before creating source S3 bucket. This cloudformation
 must run on a region other than the region where source bucket is located'

Parameters:
  bucketName:
    Description: Name of the destination S3 bucket
    Type: String
  accountID:
    Description: Account number of the source S3 bucket
    Type: String

Resources:
  # Creating destination S3 bucket
  s3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketName
      Tags:
        - Key: Name
          Value: !Ref bucketName
      VersioningConfiguration:
        Status: Enabled
  # Bucket policy for granting replication access from source account
  destReplPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref bucketName
      PolicyDocument:
        Statement:
          - Action:
              - 's3:ReplicateObject'
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:iam::"
                    - !Ref accountID
                    - ":root"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  - !Ref bucketName
                  - "/*"
          -
            Action:
              - 's3:PutObject'
            Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: "*"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  - !Ref bucketName
                  - "/*"
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: AES256
          -
            Action:
              - 's3:PutObject'
            Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  - !Ref bucketName
                  - "/*"
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: true
    DependsOn: s3bucket
